### ISSUE TITLE
window10 Build-Dependencies.ps1 bug

### ISSUE THREAD

**Issue by zn123** [obsproject/obs-deps#119]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

 Build-Main      |  ~~~~~~~~~~      | A Visual Studio installation (2019 or newer) is required for this build script. The Visual Studio      | Community edition is available for free at https://visualstudio.microsoft.com/vs/community/.  If      | Visual Studio is indeed installed, locate the directory      | 'C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.VisualStudio.Setup.WMIProvider,Version=xxxx'      | right-click the file 'Microsoft.Visualstudio.Setup.WMIProvider.msi' and choose 'repair'.

### Expected Behavior

buid

### Current Behavior

PS D:\Program Files\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build> .\vcvars64.bat
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.16
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
PS D:\Program Files\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build> e:
PS E:\temp_qt\OBS\obs-deps> .\Build-Dependencies.ps1
---------------------------------------------------------------------------------------------------
[OBS-DEPS] - configuration Release, target x64, shared libraries No
Dependencies: All
---------------------------------------------------------------------------------------------------
    =>   Check for Git executable
     >   Git found
     >   Found dependency 7z as C:\Program Files (x86)\7-Zip\7z.exe
     >   Found dependency cmake as C:\Program Files\CMake\bin\cmake.exe
---------------------------------------------------------------------------------------------------
[OBS-DEPS] Error(s) occurred:
---------------------------------------------------------------------------------------------------
Exception: E:\temp_qt\OBS\obs-deps\Build-Dependencies.ps1:184
Line |
 184 |  Build-Main
     |  ~~~~~~~~~~
     | A Visual Studio installation (2019 or newer) is required for this build script. The Visual Studio
     | Community edition is available for free at https://visualstudio.microsoft.com/vs/community/.  If
     | Visual Studio is indeed installed, locate the directory
     | 'C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.VisualStudio.Setup.WMIProvider,Version=xxxx'
     | right-click the file 'Microsoft.Visualstudio.Setup.WMIProvider.msi' and choose 'repair'.

PS E:\temp_qt\OBS\obs-deps>

### Steps to Reproduce

1.
PS D:\Program Files\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build> .\vcvars64.bat
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.16
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
2.
PS E:\temp_qt\OBS\obs-deps> .\Build-Dependencies.ps1
---------------------------------------------------------------------------------------------------
[OBS-DEPS] - configuration Release, target x64, shared libraries No
Dependencies: All
---------------------------------------------------------------------------------------------------
    =>   Check for Git executable
     >   Git found
     >   Found dependency 7z as C:\Program Files (x86)\7-Zip\7z.exe
     >   Found dependency cmake as C:\Program Files\CMake\bin\cmake.exe
---------------------------------------------------------------------------------------------------
[OBS-DEPS] Error(s) occurred:
---------------------------------------------------------------------------------------------------
Exception: E:\temp_qt\OBS\obs-deps\Build-Dependencies.ps1:184
Line |
 184 |  Build-Main
     |  ~~~~~~~~~~
     | A Visual Studio installation (2019 or newer) is required for this build script. The Visual Studio
     | Community edition is available for free at https://visualstudio.microsoft.com/vs/community/.  If
     | Visual Studio is indeed installed, locate the directory
     | 'C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.VisualStudio.Setup.WMIProvider,Version=xxxx'
     | right-click the file 'Microsoft.Visualstudio.Setup.WMIProvider.msi' and choose 'repair'.

3.
...

**Comment by zn123** [comment]
PS E:\temp_qt\OBS\obs-deps> Get-CimInstance MSFT_VSInstance

Caption           : Visual Studio Community 2019
Description       : 功能强大的 IDE，供学生、开放源代码参与者和个人免费使用
ElementName       : Visual Studio Community 2019
InstanceID        : Microsoft:VisualStudio:3423fc0c
IdentifyingNumber : 3423fc0c
Name              : Visual Studio Community 2019
SKUNumber         :
Vendor            : Microsoft Corporation
Version           : 16.11.32602.291
WarrantyDuration  :
WarrantyStartDate :
ChannelId         : VisualStudio.16.Release
ChannelUri        : https://aka.ms/vs/16/release/channel
InstallDate       : 2022/1/5 15:00:48
InstallLocation   : d:\Program Files\Microsoft Visual Studio\2019\Community
IsComplete        : True
IsLaunchable      : True
IsPrerelease      : False
LayoutPath        :
ProductId         : Microsoft.VisualStudio.Product.Community
ProductLocation   : d:\Program Files\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe
State             : 4294967295
PSComputerName    :

Caption           : Visual Studio Community 2017
Description       : 适用于学生、开放源代码和个体开发人员的免费、全功能型 IDE
ElementName       : Visual Studio Community 2017
InstanceID        : Microsoft:VisualStudio:83b80a1e
IdentifyingNumber : 83b80a1e
Name              : Visual Studio Community 2017
SKUNumber         :
Vendor            : Microsoft Corporation
Version           : 15.9.28307.2019
WarrantyDuration  :
WarrantyStartDate :
ChannelId         : VisualStudio.15.Release
ChannelUri        : https://aka.ms/vs/15/release/channel
InstallDate       : 2021/1/12 16:47:32
InstallLocation   : D:\Program Files\Microsoft Visual Studio\2017\Community
IsComplete        : True
IsLaunchable      : True
IsPrerelease      : False
LayoutPath        :
ProductId         : Microsoft.VisualStudio.Product.Community
ProductLocation   : D:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
State             : 4294967295
PSComputerName    :

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by zn123** [comment]
i want build  obs-deps

**Comment by RytoEX** [comment]
> i want build obs-deps

The obs-deps Windows build scripts were designed to support systems with only VS2019 installed. That said, PR #108 is already in progress to better address systems that have multiple Visual Studio installations.

**Comment by zn123** [comment]
function Find-VisualStudio {
    <#
        .SYNOPSIS
            Finds available Visual Studio instance.
        .DESCRIPTION
            Uses WMI (Windows Management Instrumentation) to find an installed
            Visual Studio instance on the host system.
        .EXAMPLE
            Find-VisualStudio
    #>

    $VisualStudioData = Get-CimInstance MSFT_VSInstance
	Log-Status $VisualStudioData.Version
	
    if ( ! ( $VisualStudioData ) -or ( $VisualStudioData.Version -lt 16 ) ) {
        $ErrorMessage = @(
            "A Visual Studio installation (2019 or newer) is required for this build script.",
            "The Visual Studio Community edition is available for free at https://visualstudio.microsoft.com/vs/community/.",
            "",
            "If Visual Studio is indeed installed, locate the directory ",
            " 'C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.VisualStudio.Setup.WMIProvider,Version=xxxx'",
            " right-click the file 'Microsoft.Visualstudio.Setup.WMIProvider.msi' and choose 'repair'."
        )

        throw $ErrorMessage
    }

    return $VisualStudioData
}

**Comment by zn123** [comment]
$VisualStudioData = Get-CimInstance MSFT_VSInstance
	Log-Status $VisualStudioData.Version

     >   16.11.32602.291
     >   15.9.28307.2019

**Comment by Fenrirthviti** [comment]
Please stop just spamming console output. If you need help with repairing your environment, use the forums or Discord.
