### ISSUE TITLE
Error when compiling obs with advanced scene switcher plugin using qt generated by script compiler.

### ISSUE THREAD

**Issue by littlebigghost** [obsproject/obs-deps#209]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0-beta2

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

。

### Expected Behavior

I'm hoping that the qt generated by compiling with the method provided in the script will successfully compile the obs with the advanced scene switcher plugin

### Current Behavior

I use the provided script to compile qt6.4.3 under windows, it can be compiled successfully, but when I use the compiled qt to compile OBS with Advanced Scene Switcher, it will report fatal error C1083: Cannot open include file: 'curl/curl.h': No such file or directory: 'curl/curl.h'. No such file or directory. but when I use the qt installer for msvc2019 to compile OBS with Advanced Scene Switcher, it doesn't give me any error!

The following is a partial error log at compile time:
35>D:\git\obs-studio\UI\frontend-plugins\SceneSwitcher\src\switcher-data-structs.hpp(8,10): fatal  error C1083: Cannot open include file: 'curl/curl.h': No such file or directory (compiling source file D:\git\obs-studio\UI\frontend-plugins\SceneSwitcher\src\general.cpp)
35>switch-audio.cpp
45>util.cpp
45>platform.cpp
42>libobs-opengl.vcxproj -> D:\build\obs\libobs-opengl\Debug\libobs-opengl.dll
47>aja-vpid-data.cpp
47>aja-widget-io.cpp
35>D:\git\obs-studio\UI\frontend-plugins\SceneSwitcher\src\switcher-data-structs.hpp(8,10): fatal  error C1083: Cannot open include file: 'curl/curl.h': No such file or directory (compiling source file D:\git\obs-studio\UI\frontend-plugins\SceneSwitcher\src\legacy\scene-trigger.cpp)

### Steps to Reproduce

1.Generate qt by script compilation
2.Compiling obs with advanced scene switcher plugin using compiled qt

**Comment by Fenrirthviti** [comment]
We do not support the advanced scene switcher plugin, please contact the advanced scene switcher developer for further assistance building their plugin
