### ISSUE TITLE
fail to build carla x64. fatal   error C1083: Cannot open include file: 'serd/serd.h':

### ISSUE THREAD

**Issue by shijunz** [obsproject/obs-deps#229]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

no

### Expected Behavior

Build carla ok

### Current Behavior

         Initializing build
HEAD is now at cb7f1a975 cmake: try another mac approach
  carla  =>   Checked out commit cb7f1a975790dda458481e88de0a29c433b706c9 on branch master
  carla  =>   Configure (x64)
Not searching for unused variables given on the command line.
-- Checking for module 'fluidsynth'
--   Package 'fluidsynth', required by 'virtual:world', not found
-- Checking for module 'sndfile'
--   Package 'sndfile', required by 'virtual:world', not found
-- Configuring done (8.8s)
-- Generating done (1.1s)
-- Build files have been written to: C:/tools/alpaca/obs/obs-deps/windows_build_temp/Carla/build_x64
  carla  =>   Build (x64)
MSBuild version 17.7.2+d6990bcfa for .NET Framework

  carla-audio-decoder.vcxproj -> C:\tools\alpaca\obs\obs-deps\windows_build_temp\Carla\build_x64\Release\carla-audio-de
  coder.lib
  carla-jackbridge.vcxproj -> C:\tools\alpaca\obs\obs-deps\windows_build_temp\Carla\build_x64\Release\carla-jackbridge.
  lib
  carla-lilv_serd.vcxproj -> C:\tools\alpaca\obs\obs-deps\windows_build_temp\Carla\build_x64\Release\carla-lilv_serd.li
  b
  sord.c
C:\tools\alpaca\obs\obs-deps\windows_build_temp\Carla\cmake\..\source\modules\lilv\sord-0.16.0\sord/sord.h(28,1): fatal
  error C1083: Cannot open include file: 'serd/serd.h': No such file or directory [C:\tools\alpaca\obs\obs-deps\windows
_build_temp\Carla\build_x64\carla-lilv_sord.vcxproj]
  sratom.c
C:\tools\alpaca\obs\obs-deps\windows_build_temp\Carla\cmake\..\source\modules\lilv\sratom-0.6.0\sratom/sratom.h(29,1):
fatal  error C1083: Cannot open include file: 'serd/serd.h': No such file or directory [C:\tools\alpaca\obs\obs-deps\wi
ndows_build_temp\Carla\build_x64\carla-lilv_sratom.vcxproj]
  pthreads4w.vcxproj -> C:\tools\alpaca\obs\obs-deps\windows_build_temp\Carla\build_x64\Release\pthreads4w.lib
  carla-native-plugins.vcxproj -> C:\tools\alpaca\obs\obs-deps\windows_build_temp\Carla\build_x64\Release\carla-native-
  plugins.lib
  carla-rtmempool.vcxproj -> C:\tools\alpaca\obs\obs-deps\windows_build_temp\Carla\build_x64\Release\carla-rtmempool.li
  b
  carla-sfzero.vcxproj -> C:\tools\alpaca\obs\obs-deps\windows_build_temp\Carla\build_x64\Release\carla-sfzero.lib
  carla-water.vcxproj -> C:\tools\alpaca\obs\obs-deps\windows_build_temp\Carla\build_x64\Release\carla-water.lib
  carla-ysfx.vcxproj -> C:\tools\alpaca\obs\obs-deps\windows_build_temp\Carla\build_x64\Release\carla-ysfx.lib
  carla-zita-resampler.vcxproj -> C:\tools\alpaca\obs\obs-deps\windows_build_temp\Carla\build_x64\Release\carla-zita-re
  sampler.lib
  carla-water-files.vcxproj -> C:\tools\alpaca\obs\obs-deps\windows_build_temp\Carla\build_x64\Release\carla-water-file
  s.lib
---------------------------------------------------------------------------------------------------
[OBS-DEPS] Error(s) occurred:
---------------------------------------------------------------------------------------------------
Write-Error: C:\tools\alpaca\obs\obs-deps\Build-Dependencies.ps1:238
Line |
 238 |  Build-Main
     |  ~~~~~~~~~~
     | Error during build step Build - cmake --build build_x64 --config Release exited with non-zero code 1.

### Steps to Reproduce

1. git clone https://github.com/obsproject/obs-deps
2. enter obs-deps
3..\Build-Dependencies.ps1
...

**Comment by RytoEX** [comment]
That is due to this: https://github.com/falkTX/Carla/issues/1179

If you enable core.symlinks in your git config, it _may_ work.

Regardless, this is moot as we are removing Carla with #227.

**Comment by shijunz** [comment]
> That is due to this: [falkTX/Carla#1179](https://github.com/falkTX/Carla/issues/1179)
> 
> If you enable core.symlinks in your git config, it _may_ work.
> 
> Regardless, this is moot as we are removing Carla with #227.

thanks, @227 is ok,
