### ISSUE TITLE
build script for macos-01.sh finishes with errors

### ISSUE THREAD

**Issue by DAConsulting** [obsproject/obs-deps#48]
build step macos-01 finishes with errors

## Platform

Operating system and version:

Mac OSX 10.15
OBS Studio version: n/a

## Expected Behavior

build step should finish without errors

## Current Behavior

gcc -I/tmp/obsdeps/include -Wall -W -I. -I/usr/local/opt/qt/include  -c -o cleanup.o ../../CCache/cleanup.c
In file included from ../../CCache/execute.c:19:
In file included from ../../CCache/mdfour.c../../CCache/ccache.h::20161:
:5: ../../CCache/ccache.h:161error:: 5: errorexpected:  parameter declaratorexpected
 parameter declarator
int snprintf(char *,size_t ,const char *, ...);
int snprintf(char *,size_t ,const char *, ...);
    ^
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h::5757::3939::  notenote: : expandedexpanded  fromfrom  macromacro

            'snprintf''snprintf'

  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                      ^  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)

                                      ^
In file included from ../../CCache/execute.c:19:
In file included from ../../CCache/mdfour.c../../CCache/ccache.h::20161:
:5../../CCache/ccache.h:: 161:5error::  expectederror : ')'
expected ')'/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h
:57:39:/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h :57:note39: : expanded fromnote : macro
expanded       'snprintf'from 
macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                      ^
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
../../CCache/ccache.h                                      ^:
161:5:In file included from  ../../CCache/ccache.c../../CCache/ccache.h::24note161:
: :5to:match this '('
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:28: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                           ^
[1m../../CCache/ccache.h:161:5: error: expected parameter declarator
In file included from ../../CCache/execute.c:19:
../../CCache/ccache.h:161:5:  error: note: conflicting totypes  int snprintf(char *,size_t ,const char *, ...);matchfor
  '__builtin___snprintf_chk'this    ^ 

'('
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:28/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:: int snprintf(char *,size_t ,const char *, ...);57
:39note::     ^ 
expanded notefrom:  macro/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.hexpanded
:       57from'snprintf': 3macro
:
       'snprintf'note
: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                           ^
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                      ^
In file included from ../../CCache/hash.c:22:
../../CCache/ccache.h:161:5: error: expected parameter declarator
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
int snprintf(char *,size_t ,const char *, ...);
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:39: note: expanded from macro
      'snprintf'
../../CCache/ccache.h:161:5: note:   __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)'__builtin___snprintf_chk'
 is                                      ^ 
a builtin with In file included from type../../CCache/hash.c: 22'int:
 (char../../CCache/ccache.h :*,161 :unsigned5 :long,  int,error
:       unsigned expectedlong,  ')'const In file included from 
char../../CCache/ccache.c :*,24 /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:
...)':57../../CCache/ccache.h
::39161:: 5/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:: 57note:: 3error:expanded:   from expectedmacronote 
: ')'      'snprintf'expanded
 
from macro/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h
:      57'snprintf':39
: note: expanded from macro
      'snprintf'  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)

                                      ^
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)../../CCache/ccache.h
:161  ^:
5: note:   __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)to
 match                                      ^ 
this '('
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h../../CCache/ccache.h::57161::285::  notenote: : expandedto  frommatch  macrothis
       '(''snprintf'

/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:28: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                           ^
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                           ^
In file included from ../../CCache/hash.c:22:
../../CCache/ccache.h:161:5: error: conflicting types for '__builtin___snprintf_chk'
int snprintf(char *,size_t ,const char *, ...);
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:3:In file included from  ../../CCache/ccache.c:24note:
: ../../CCache/ccache.hexpanded: 161from: 5macro:
       'snprintf'error
: conflicting types for '__builtin___snprintf_chk'
In file included from   __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
../../CCache/mdfour.c:  ^20
:
int snprintf(char *,size_t ,const char *, ...);
../../CCache/ccache.h    ^:
161:5: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:error57: :3:conflicting  types notefor:  '__builtin___snprintf_chk'expanded 
from macro
      'snprintf'
../../CCache/ccache.h:161:5int snprintf(char *,size_t ,const char *, ...);:
     ^note
:   __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
../../CCache/ccache.h:161:5: note: '__builtin___snprintf_chk' is a builtin with type 'int (char *, unsigned long, int,
      unsigned long, const char/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h :*,57 :...)'3:
 note: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57expanded: 3from:  macro
      note'snprintf': 
expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
../../CCache/ccache.h:161:5: note: '__builtin___snprintf_chk' is a builtin with type 'int (char *, unsigned long, int,
      unsigned long, const char *, ...)'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:3: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
3 errors generated.
'__builtin___snprintf_chk' is a builtin with type 'int (char *, unsigned long, int,
      unsigned long, const char *, ...)'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:3: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
../../CCache/ccache.c:126:32: error: use of undeclared identifier 'PROGRAM_NAME'
                char *p = find_executable(e, MYNAME);
                                             ^
../../CCache/ccache.h:54:16: note: expanded from macro 'MYNAME'
#define MYNAME PROGRAM_NAME
               ^
3 errors generated.
In file included from ../../CCache/args.c:21:
../../CCache/ccache.h:161:5: error: expected parameter declarator
int snprintf(char *,size_t ,const char *, ...);
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:39: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                      ^
In file included from ../../CCache/args.c:21:
../../CCache/ccache.h:161:5: error: expected ')'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:39: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                      ^
../../CCache/ccache.h:161:5: note: to match this '('
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:28: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                           ^
In file included from ../../CCache/args.c:21:
../../CCache/ccache.h:161:5: error: conflicting types for '__builtin___snprintf_chk'
int snprintf(char *,size_t ,const char *, ...);
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:3: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
../../CCache/ccache.h:161:5: note: '__builtin___snprintf_chk' is a builtin with type 'int (char *, unsigned long, int,
      unsigned long, const char *, ...)'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:3: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
In file included from ../../CCache/util.c:19:
../../CCache/ccache.h:161:5: error: expected parameter declarator
int snprintf(char *,size_t ,const char *, ...);
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:39: note: expanded from macro
      'snprintf'
make[1]: *** [execute.o] Error 1
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                      ^
In file included from ../../CCache/util.c:19:
../../CCache/ccache.h:161:5: make[1]: *** Waiting for unfinished jobs....
error: expected ')'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:39: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                      ^
../../CCache/ccache.h:161:5: note: to match this '('
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:28: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                           ^
In file included from ../../CCache/util.c:19:
../../CCache/ccache.h:161:5: error: conflicting types for '__builtin___snprintf_chk'
int snprintf(char *,size_t ,const char *, ...);
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:3: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
../../CCache/ccache.h:161:5: note: '__builtin___snprintf_chk' is a builtin with type 'int (char *, unsigned long, int,
      unsigned long, const char *, ...)'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:3: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
3 errors generated.
3 errors generated.
make[1]: *** [hash.o] Error 1
../../CCache/ccache.c:772:19: error: use of undeclared identifier 'PROGRAM_NAME'
        if (strcmp(base, MYNAME) == 0) {
                         ^
../../CCache/ccache.h:54:16: note: expanded from macro 'MYNAME'
#define MYNAME PROGRAM_NAME
               ^
../../CCache/ccache.c:792:45: 3error error: s generated.
use of undeclared identifier 'PROGRAM_NAME'
In file included from ../../CCache/stats.c        orig_args->argv[0] = find_executable(base, MYNAME);:
25:
                                                   ^
../../CCache/ccache.h:161:5../../CCache/ccache.h:: 54:16error::  note: expectedexpanded  parameterfrom  declaratormacro 
'MYNAME'
#define MYNAME PROGRAM_NAME
               ^
int snprintf(char *,size_t ,const char *, ...);
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:39: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                      ^
In file included from ../../CCache/stats.c:25:
../../CCache/ccache.h:161:5: error: expected ')'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:39: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                      ^
../../CCache/ccache.h:161:5: note: to match this '('
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:28: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                           ^
In file included from ../../CCache/stats.c:25:
../../CCache/ccache.h:161:5: error: conflicting types for '__builtin___snprintf_chk'
int snprintf(char *,size_t ,const char *, ...);
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:3: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
../../CCache/ccache.h:161:5: note: '__builtin___snprintf_chk' is a builtin with type 'int (char *, unsigned long, int,
      unsigned long, const char *, ...)'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:3: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
make[1]: *** [mdfour.o] Error 1
make[1]: *** [args.o] Error 1
make[1]: *** [util.o] Error 1
3 errors generated.
../../CCache/ccache.c:1121:32: error: use of undeclared identifier 'PROGRAM_NAME'
                char *p = find_executable(e, MYNAME);
                                             ^
../../CCache/ccache.h:54:16: note: expanded from macro 'MYNAME'
#define MYNAME PROGRAM_NAME
               ^
../../CCache/ccache.c:1200:74: error: use of undeclared identifier 'PROGRAM_NAME'
        printf("%s, a compiler cache including support for SWIG. Version %s\n", MYNAME, CCACHE_VERSION);
                                                                                ^
../../CCache/ccache.h:54:16: note: expanded from macro 'MYNAME'
#define MYNAME PROGRAM_NAME
               ^
../../CCache/ccache.c:1204:14: error: expected ')'
        printf("\t" MYNAME " [options]\n");
                    ^
../../CCache/ccache.h:54:16: note: expanded from macro 'MYNAME'
#define MYNAME PROGRAM_NAME
               ^
../../CCache/ccache.c:1204:8: note: to match this '('
        printf("\t" MYNAME " [options]\n");
              ^
../../CCache/ccache.c:1205:14: error: expected ')'
        printf("\t" MYNAME " compiler [compile options]\n");
                    ^
../../CCache/ccache.h:54:16: note: expanded from macro 'MYNAME'
#define MYNAME PROGRAM_NAME
               ^
../../CCache/ccache.c:1205:8: note: to match this '('
        printf("\t" MYNAME " compiler [compile options]\n");
              ^
make[1]: *** [stats.o] Error 1
../../CCache/ccache.c:1235:30: error: use of undeclared identifier 'PROGRAM_NAME'
                        printf("%s version %s\n", MYNAME, CCACHE_VERSION);
                                                  ^
../../CCache/ccache.h:54:16: note: expanded from macro 'MYNAME'
#define MYNAME PROGRAM_NAME
               ^
../../CCache/ccache.c:1359:32: error: use of undeclared identifier 'PROGRAM_NAME'
        if (strlen(argv[0]) >= strlen(MYNAME) &&
                                      ^
../../CCache/ccache.h:54:16: note: expanded from macro 'MYNAME'
#define MYNAME PROGRAM_NAME
               ^
../../CCache/ccache.c:1360:48: error: use of undeclared identifier 'PROGRAM_NAME'
            strcmp(argv[0] + strlen(argv[0]) - strlen(MYNAME), MYNAME) == 0) {
                                                      ^
../../CCache/ccache.h:54:16: note: expanded from macro 'MYNAME'
#define MYNAME PROGRAM_NAME
               ^
../../CCache/ccache.c:1360:57: error: use of undeclared identifier 'PROGRAM_NAME'
            strcmp(argv[0] + strlen(argv[0]) - strlen(MYNAME), MYNAME) == 0) {
                                                               ^
../../CCache/ccache.h:54:16: note: expanded from macro 'MYNAME'
#define MYNAME PROGRAM_NAME
               ^
14 errors generated.
In file included from ../../CCache/cleanup.c:22:
../../CCache/ccache.h:161:5: error: expected parameter declarator
int snprintf(char *,size_t ,const char *, ...);
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:39: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                      ^
In file included from ../../CCache/cleanup.c:22:
../../CCache/ccache.h:161:5: error: expected ')'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:39: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                      ^
../../CCache/ccache.h:161:5: note: to match this '('
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:28: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                           ^
In file included from ../../CCache/cleanup.c:22:
../../CCache/ccache.h:161:5: error: conflicting types for '__builtin___snprintf_chk'
int snprintf(char *,size_t ,const char *, ...);
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:3: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
../../CCache/ccache.h:161:5: note: '__builtin___snprintf_chk' is a builtin with type 'int (char *, unsigned long, int,
      unsigned long, const char *, ...)'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:3: note: expanded from macro
      'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
3 errors generated.
make[1]: *** [ccache.o] Error 1
make[1]: *** [cleanup.o] Error 1
make: *** [ccache] Error 2
## Steps to Reproduce

1.  Follow instrucdtions to install pre-reqs as described
2.  Run 'bash ./build-script-macos-01.sh,

**Comment by PatTheMav** [comment]
Would be much appreciated if you could re-format your post to make it more readable (e.g. attach the error log as a text file instead). Also looks more like an issue with CCache - maybe try commenting out this line and running the script again:

https://github.com/obsproject/obs-deps/blob/a2c0cec728be6614146aac16289c0d27daffd07c/build-script-macos-01.sh#L54

**Comment by PatTheMav** [comment]
No feedback in ~4 months, closing.
